name: Deploy to Zizi Bot

on:
  push:
    branches: [ stable ]

jobs:
  build:
    name: Deploy Zizi Bot
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
      #     - name: Prepare Build
      #       uses: actions/checkout@v2
      #     - name: Setup .NET
      #       uses: actions/setup-dotnet@v1
      #       with:
      #         dotnet-version: 6.0.x

      #     - name: Restore dependencies
      #       run: dotnet restore
      #     - name: Publish
      #       run: dotnet publish src/WinTenDev.ZiziBot.AppHost -r linux-x64 -c Release --self-contained=false /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true -o build/zizi-bot

      - name: Send notify to Telegram before deployment
        uses: appleboy/telegram-action@v0.1.1
        with:
          # telegram user
          to: ${{ secrets.TG_LOG_CHAT_ID }}
          # telegram token
          token: ${{ secrets.TG_DEV_BOT_TOKEN }}
          # telegram message
          message: |
            Zizi Bot entering Maintenance Mode
          # disables link previews for links in this message
          disable_web_page_preview: true

      - name: Copy Binary from Beta
        # You may pin to the exact commit or the version.
        # uses: cross-the-world/ssh-pipeline@7f022867934a210af826af99ef80d96f03a094d5
        uses: cross-the-world/ssh-pipeline@v1.2.0
        with:
          # ssh remote host
          host: ${{ secrets.VPS_HOST }}
          # ssh remote port
          port: 22
          # ssh remote user
          user: ${{ secrets.VPS_USER }}
          # ssh remote password
          pass: ${{ secrets.VPS_PASS }}
          # execute commands on ssh
          script: |
            ${{ secrets.CMD_STOP_ZIZIBOT }}
            cp -R ${{ secrets.VPS_REMOTE_DIR }}/Storage/Language/* ${{ secrets.VPS_REMOTE_DIR_STABLE }}/Storage/Language/
            cp ${{ secrets.VPS_REMOTE_DIR }}/WinTenDev.ZiziBot.AppHost ${{ secrets.VPS_REMOTE_DIR_STABLE }}/WinTenDev.ZiziBot.AppHost
            ${{ secrets.CMD_START_ZIZIBOT }}

      #     - name: ssh-scp-ssh-pipelines
      #       # You may pin to the exact commit or the version.
      #       # uses: cross-the-world/ssh-scp-ssh-pipelines@78e864b4890087a58248ff39320406971ca88b89
      #       uses: cross-the-world/ssh-scp-ssh-pipelines@v1.1.4
      #       with:
      #         # ssh remote host
      #         host: ${{ secrets.VPS_HOST }}
      #         # ssh remote user
      #         user: ${{ secrets.VPS_USER }}
      #         # ssh remote password
      #         pass: ${{ secrets.VPS_PASS }}
      #         # execute pre-commands before scp
      #         first_ssh: ${{ secrets.CMD_STOP_ZIZIBOT }}
      #         # scp from local to remote
      #         scp: |
      #           build/zizi-bot/* => ${{ secrets.VPS_REMOTE_DIR_STABLE }}
      #         # execute post-commands after scp
      #         last_ssh: ${{ secrets.CMD_START_ZIZIBOT }}

      - name: Update Release Tag
        uses: oprypin/find-latest-tag@v1
        id: current_release
        with:
          repository: ${{ github.server_url }}/${{ github.repository }}
          release-only: true

      - run: echo "Latest release at version ${{ steps.octokit.outputs.tag }}"

      - name: update release
        id: update_release
        uses: tubone24/update_release@v1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          TAG_NAME: ${{ steps.current_release.outputs.tag }}
        with:
          prerelease: false

      - name: Send notify to Telegram after deployment
        uses: appleboy/telegram-action@v0.1.1
        with:
          # telegram user
          to: ${{ secrets.TG_LOG_CHAT_ID }}
          # telegram token
          token: ${{ secrets.TG_DEV_BOT_TOKEN }}
          # telegram message
          message: |
            Zizi Bot Deployment success
            Repo: ${{ github.repository }}
            Changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
          # disables link previews for links in this message
          disable_web_page_preview: true
