name: Sync to Other Repo

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Sync To Mirror
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
          
      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build project
        run: dotnet build src/WinTenDev.ZiziBot.AppHost
        
      - name: Run Mirror repository
        uses: yesolutions/mirror-action@v0.5.0
        with:
          REMOTE: ${{ secrets.GIT_ZIZI_MIRROR_REPO }}
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
          DEBUG: true
