name: Sync to Mirror

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      #     - name: Test
      #       run: dotnet test --no-build --verbosity normal
      - name: mirror-repository
        uses: spyoungtech/mirror-action@v0.4.3
        with:
          # The remote repository e.g. https://github.com/octocat/foo.git or git@github.com:octocat/foo.git
          REMOTE: 'https://github.com/WinTenDev/ZiziBot.NET-Mirror.git'
          GIT_USERNAME: azhe403
          GIT_PASSWORD: ${{ secrets.GIT_PASS }}
          # set to "true" to enable debug mode
          DEBUG: false
      
