name: Sync to Other Repo

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Sync To Mirror
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build src/WinTenDev.ZiziBot.AppHost

      - name: Clone from Mirror
        uses: actions/checkout@v2
        with:
          repository: ${{secrets.GIT_ZIZI_MIRROR_REPO}}
          token: ${{ secrets.GH_PAT }}
          path: ./mirror

      - name: Sync to Mirror
        run: |
          cd ./mirror
          git config --global user.email "fulan@winten.my.id"
          git config --global user.name "Fulan bin Fulan"
          git remote add upstream ${{ github.server_url }}/${{ github.repository }}
          git checkout main
          git rebase upstream/main -X theirs
          git push origin main --force
