name: Zizi Bot Alpha

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  zizibot-linux64-fd-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /home/runner/work/ZiziBot.NET/ZiziBot.NET

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Install dependencies
        run: dotnet restore WinTenDev.ZiziBot.sln

      - name: Linux64 FD Build
        run: dotnet publish src/WinTenDev.ZiziBot.App -r linux-x64 -c Release --self-contained=false
      - name: Upload Linux64 Artifacs
        uses: actions/upload-artifact@v2
        with:
          name: zizibot-linux64-fd-build.zip
          path: src/WinTenDev.ZiziBot.App/bin/Release/net6.0/linux-x64/publish

  zizibot-linux64-sf-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /home/runner/work/ZiziBot.NET/ZiziBot.NET

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Install dependencies
        run: dotnet restore WinTenDev.ZiziBot.sln

      - name: Linux64 FD Single-File Build
        run: dotnet publish src/WinTenDev.ZiziBot.App -r linux-x64 -c Release --self-contained=false /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true
      - name: Upload Linux64 Single-File Artifacs
        uses: actions/upload-artifact@v2
        with:
          name: zizibot-linux64-sf-build.zip
          path: src/WinTenDev.ZiziBot.App/bin/Release/net6.0/linux-x64/publish

  zizibot-win64-fd-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /home/runner/work/ZiziBot.NET/ZiziBot.NET

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Install dependencies
        run: dotnet restore WinTenDev.ZiziBot.sln
      - name: Win64 FD Build
        run: dotnet publish src/WinTenDev.ZiziBot.App -r win-x64 -c Release --self-contained=false
      - name: Upload Win64 FD Artifacs
        uses: actions/upload-artifact@v2
        with:
          name: zizibot-win64-fd-build.zip
          path: src/WinTenDev.ZiziBot.App/bin/Release/net6.0/win-x64/publish

  zizibot-win64-sf-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /home/runner/work/ZiziBot.NET/ZiziBot.NET

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Install dependencies
        run: dotnet restore WinTenDev.ZiziBot.sln

      - name: Win64 FD Single-File Build
        run: dotnet publish src/WinTenDev.ZiziBot.App -r win-x64 -c Release --self-contained=false /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true
      - name: Upload Win64 SF Artifacs
        uses: actions/upload-artifact@v2
        with:
          name: zizibot-win64-sf-build.zip
          path: src/WinTenDev.ZiziBot.App/bin/Release/net6.0/win-x64/publish